"""
ADC Daily AI Infrastructure Briefing Generator
Scans 15+ news categories relevant to ADC operations.
Run every morning: python scripts/daily_briefing.py

Outputs to data/daily-briefing-YYYY-MM-DD.md
Can also feed into AI Daily Omniverse / Ground Zero content pipeline.
"""

import os
import json
import datetime
import httpx

# News categories to scan
SCAN_CATEGORIES = [
    {"query": "NVIDIA AI factory news", "tag": "NVIDIA", "relevance": "CRITICAL"},
    {"query": "AI data center construction 2026", "tag": "AI Infrastructure", "relevance": "HIGH"},
    {"query": "Terafab xAI chip manufacturing", "tag": "Terafab", "relevance": "CRITICAL"},
    {"query": "NemoClaw OpenClaw NVIDIA update", "tag": "NemoClaw", "relevance": "HIGH"},
    {"query": "Skydio drone military contract", "tag": "Skydio/KLFT", "relevance": "HIGH"},
    {"query": "Louisiana AI infrastructure investment", "tag": "Louisiana", "relevance": "CRITICAL"},
    {"query": "FAA Part 108 BVLOS drone rule", "tag": "FAA/Drones", "relevance": "HIGH"},
    {"query": "800V DC data center power architecture", "tag": "Power", "relevance": "MEDIUM"},
    {"query": "CoreWeave Crusoe Energy neocloud", "tag": "Competition", "relevance": "HIGH"},
    {"query": "Hut 8 Meta Amazon Louisiana data center", "tag": "Louisiana Competition", "relevance": "HIGH"},
    {"query": "Jensen Huang NVIDIA announcement", "tag": "NVIDIA Leadership", "relevance": "HIGH"},
    {"query": "CHIPS Act funding semiconductor", "tag": "Federal Policy", "relevance": "MEDIUM"},
    {"query": "Henry Hub natural gas price today", "tag": "Energy", "relevance": "MEDIUM"},
    {"query": "First Solar panel manufacturing", "tag": "Solar", "relevance": "MEDIUM"},
    {"query": "Eaton power distribution data center", "tag": "Vendors", "relevance": "MEDIUM"},
    {"query": "airport AI ground traffic management", "tag": "Airport AI", "relevance": "HIGH"},
    {"query": "Vera Rubin NVL72 GPU availability", "tag": "Hardware", "relevance": "CRITICAL"},
]

# Story Pipeline categories for Ground Zero / AI Daily Omniverse
STORY_RATINGS = {
    "CRITICAL": "Lead story — requires immediate coverage or action",
    "HIGH": "Strong story — cover within 24 hours",
    "MEDIUM": "Background story — monitor, cover if slow news day",
    "LOW": "File for reference — may become relevant later",
}


def generate_briefing_header(date_str):
    return f"""# ADC Daily Briefing — {date_str}
Mission Control | Advantage Design & Construction
Generated by AI Daily Omniverse Scanner

---

## Quick Stats
- Scan categories: {len(SCAN_CATEGORIES)}
- Date: {date_str}
- Time: {datetime.datetime.now().strftime('%H:%M %Z')}

---

"""


def format_story(headline, source, url, summary, tag, relevance, action=None):
    action_line = f"\n**ACTION:** {action}" if action else ""
    return f"""### [{relevance}] {headline}
**Source:** [{source}]({url}) | **Category:** {tag}

{summary}{action_line}

---

"""


if __name__ == "__main__":
    today = datetime.date.today().isoformat()
    output_path = os.path.join(
        os.path.dirname(__file__), "..", "data", f"daily-briefing-{today}.md"
    )

    print(f"ADC Daily Briefing Generator — {today}")
    print(f"Scanning {len(SCAN_CATEGORIES)} categories...")
    print(f"Output: {output_path}")
    print()
    print("NOTE: This script generates the template and category structure.")
    print("The actual news scanning is done by the Claude agent using WebSearch.")
    print("Run the agent with: 'Run the daily morning scan' in Claude Code.")
    print()

    # Generate template
    briefing = generate_briefing_header(today)

    for cat in SCAN_CATEGORIES:
        briefing += f"## {cat['tag']} ({cat['relevance']})\n"
        briefing += f"Search: `{cat['query']}`\n\n"
        briefing += "*Waiting for agent scan...*\n\n---\n\n"

    briefing += """## Story Pipeline (Ground Zero / AI Daily Omniverse)

Stories rated CRITICAL or HIGH should be added to the Notion Story Pipeline for episode production.

| Rating | Meaning |
|--------|---------|
| CRITICAL | Lead story — requires immediate coverage or action |
| HIGH | Strong story — cover within 24 hours |
| MEDIUM | Background story — monitor, cover if slow news day |
| LOW | File for reference — may become relevant later |

---

## Action Items

*Extracted from scan results — items requiring Scott's attention today.*

1. [ ] Message Chancellor Dalton on LinkedIn
2. [ ] Message Kumer Pial Das on LinkedIn
3. [ ] Send 3 email blasts (136 contacts)
4. [ ] NPN registration
5. [ ] Check for NemoClaw 403 bug fix

---

*Generated by ADC Mission Control | scripts/daily_briefing.py*
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(briefing)

    print(f"Template generated: {output_path}")
    print("Run the morning scan agent to fill in the stories.")
